unpackaged/main/default/objects/Account/recordTypes/Original.recordType-meta.xml
<RecordType>
    <fullName>Original</fullName>
    <active>true</active>
    <label>Original</label>
</RecordType>

unpackaged/main/default/objects/Blood_Test__c/Blood_Test__c.object-meta.xml
<CustomObject>
    <label>Blood Test</label>
    <nameField>
        <displayFormat>BT-{000000}</displayFormat>
        <label>Blood Tests</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blood Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Blood_Test__c/fields/Analysis_Lab__c.field-meta.xml
<CustomField>
    <fullName>Analysis_Lab__c</fullName>
    <label>Analysis Lab</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>County Pathology</fullName>
            </value>
            <value>
                <fullName>Inuvi</fullName>
            </value>
            <value>
                <fullName>Randox</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Blood Tests</relationshipLabel>
    <relationshipName>Blood_Tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Haemoglobin__c.field-meta.xml
<CustomField>
    <fullName>Haemoglobin__c</fullName>
    <label>Haemoglobin</label>
    <precision>5</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Haemoglobin_Max__c.field-meta.xml
<CustomField>
    <fullName>Haemoglobin_Max__c</fullName>
    <defaultValue>TEXT(170)</defaultValue>
    <label>Haemoglobin Max</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Haemoglobin_Min__c.field-meta.xml
<CustomField>
    <fullName>Haemoglobin_Min__c</fullName>
    <defaultValue>TEXT(130)</defaultValue>
    <label>Haemoglobin Min</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Haemoglobin_Units__c.field-meta.xml
<CustomField>
    <fullName>Haemoglobin_Units__c</fullName>
    <defaultValue>&quot;g/L&quot;</defaultValue>
    <label>Haemoglobin Units</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <description>Date the Blood Test was ordered by the patient</description>
    <inlineHelpText>Date the Blood Test was ordered by the patient</inlineHelpText>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Patient_Status__c.field-meta.xml
<CustomField>
    <fullName>Patient_Status__c</fullName>
    <formula>TEXT(Contact__r.Account.PersonContact.Patient_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patient Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the Blood Test</description>
    <inlineHelpText>Status of the Blood Test</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
                <default>true</default>
                <label>Ordered</label>
            </value>
            <value>
                <fullName>Successful Test</fullName>
            </value>
            <value>
                <fullName>Partial Success/Some Failed Values</fullName>
            </value>
            <value>
                <fullName>Successful Test - Doctor Requested Repeat</fullName>
            </value>
            <value>
                <fullName>Failed Test</fullName>
            </value>
            <value>
                <fullName>Lost in post</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Received by lab</fullName>
            </value>
            <value>
                <fullName>Error - Replacement Kit Missing Patient Data</fullName>
            </value>
            <value>
                <fullName>Re-submit to RDi</fullName>
            </value>
            <value>
                <fullName>Re-submit to Inuvi</fullName>
            </value>
            <value>
                <fullName>Re-submitted to RDi</fullName>
            </value>
            <value>
                <fullName>Re-submitted to Inuvi</fullName>
            </value>
            <value>
                <fullName>Order sent to RDi</fullName>
            </value>
            <value>
                <fullName>Order sent to Real Digital</fullName>
            </value>
            <value>
                <fullName>Order sent to Inuvi</fullName>
            </value>
            <value>
                <fullName>Order sent to Randox</fullName>
            </value>
            <value>
                <fullName>Re-submit to Meddx</fullName>
            </value>
            <value>
                <fullName>Re-submitted to Meddx</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Test_Type__c.field-meta.xml
<CustomField>
    <fullName>Test_Type__c</fullName>
    <label>Test Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patient Submitted Results</fullName>
            </value>
            <value>
                <fullName>OPT013-FP</fullName>
            </value>
            <value>
                <fullName>OPT013-V</fullName>
            </value>
            <value>
                <fullName>OPT002-FP</fullName>
            </value>
            <value>
                <fullName>OPT002-V</fullName>
            </value>
            <value>
                <fullName>OPT003-FP</fullName>
            </value>
            <value>
                <fullName>OPT003-V</fullName>
            </value>
            <value>
                <fullName>OPT004-FP</fullName>
            </value>
            <value>
                <fullName>OPT004-V</fullName>
            </value>
            <value>
                <fullName>HSC1-V</fullName>
                <label>HSC1-V (FBC)</label>
            </value>
            <value>
                <fullName>OPT907-FP</fullName>
            </value>
            <value>
                <fullName>OPT907-V</fullName>
            </value>
            <value>
                <fullName>OPT908-FP</fullName>
            </value>
            <value>
                <fullName>OPT908-V</fullName>
            </value>
            <value>
                <fullName>OPT909-FP</fullName>
            </value>
            <value>
                <fullName>OPT909-V</fullName>
            </value>
            <value>
                <fullName>OPT910-FP</fullName>
            </value>
            <value>
                <fullName>OPT910-V</fullName>
            </value>
            <value>
                <fullName>OPT911-FP</fullName>
            </value>
            <value>
                <fullName>OPT911-V</fullName>
            </value>
            <value>
                <fullName>OPT912-FP</fullName>
            </value>
            <value>
                <fullName>OPT912-V</fullName>
            </value>
            <value>
                <fullName>OPT913-FP</fullName>
            </value>
            <value>
                <fullName>OPT913-V</fullName>
            </value>
            <value>
                <fullName>OPT914-FP</fullName>
            </value>
            <value>
                <fullName>OPT914-V</fullName>
            </value>
            <value>
                <fullName>OPT915-FP</fullName>
            </value>
            <value>
                <fullName>OPT915-V</fullName>
            </value>
            <value>
                <fullName>OPT916-FP</fullName>
            </value>
            <value>
                <fullName>OPT916-V</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Patient_Status__c.field-meta.xml
<CustomField>
    <fullName>Patient_Status__c</fullName>
    <label>Patient Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <color>#9999FF</color>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Blood Test</fullName>
                <color>#66FFFF</color>
                <label>Blood Test</label>
            </value>
            <value>
                <fullName>Ready for Consultation</fullName>
            </value>
            <value>
                <fullName>Consultation</fullName>
                <color>#33CCFF</color>
                <label>Consultation</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <color>#66FF99</color>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Current Patient</fullName>
                <color>#33FF33</color>
                <label>Current Patient</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <color>#FF9900</color>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <color>#FF6666</color>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Unsuitable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ASETPathologyReportControllerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 04-19-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@isTest
public class ASETPathologyReportControllerTest {
    @TestSetup static void setup(){

        Id recordTypeId  = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Original').getRecordTypeId();
        String orgId            = UserInfo.getOrganizationId(); 
        
        Account acc         = new Account(
            RecordTypeId        = recordTypeId,
            Name                = 'Test Account'
        );
        
        insert acc;

        Contact con = new Contact(
            LastName            = 'TestContact',
            Patient_Status__c   = 'Blood Test',
            AccountId           = acc.Id,
            Email               = 'contact@gmail.com'
        );

        insert con;

        Blood_Test__c bt = new Blood_Test__c(
            Order_Date__c           = System.Today(),
            Test_Type__c            = 'Patient Submitted Results',
            Haemoglobin__c          = 2.6,
            Haemoglobin_Max__c      = '4.50',
            Haemoglobin_Min__c      = '2.74',
            Haemoglobin_Units__c    = 'g/L',
            Contact__c              = con.Id,
            Analysis_Lab__c         = 'Randox',
            Status__c               = 'Successful Test'
        );

        insert bt;

    }

    @isTest static void execute(){
        List<Contact> cons = [SELECT Id FROM Contact WHERE LastName = 'TestContact' ];
        System.assertNotEquals(cons.size(), 0);

        List<Blood_Test__c> bts = [SELECT Id FROM Blood_Test__c WHERE Contact__c =: cons[0].Id ];
        System.assertNotEquals(bts.size(), 0);

        List<GeneratePDFInvocable.Requests> requestList = new List<GeneratePDFInvocable.Requests>();
        GeneratePDFInvocable.Requests req               = new GeneratePDFInvocable.Requests();
        req.recId   = bts[0].Id;
        
        requestList.add(req);

        Test.StartTest(); 
            PageReference page = Page.ASETPathologyReport; 
            Test.setCurrentPage(page);
            page.getParameters().put('Id', String.valueOf(bts[0].Id));
            
            ApexPages.StandardController sc     = new  ApexPages.StandardController(bts[0]);     
            ASETPathologyReportController ext   = new ASETPathologyReportController(sc);
            // GeneratePDFInvocable.execute(requestList);

        Test.StopTest();
    }

}