unpackaged/main/default/objects/Blood_Test__c/Blood_Test__c.object-meta.xml
<CustomObject>
    <label>Blood Test</label>
    <nameField>
        <displayFormat>BT-{000000}</displayFormat>
        <label>Blood Tests</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blood Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Blood_Test__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Blood Tests</relationshipLabel>
    <relationshipName>Blood_Tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Free_Testosterone__c.field-meta.xml
<CustomField>
    <fullName>Free_Testosterone__c</fullName>
    <description>Calculated Free Testosterone</description>
    <inlineHelpText>Calculated Free Testosterone</inlineHelpText>
    <label>Free Testosterone</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Results_Status__c.field-meta.xml
<CustomField>
    <fullName>Results_Status__c</fullName>
    <label>Results Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not sent to patient</fullName>
            </value>
            <value>
                <fullName>Checking with doctor</fullName>
            </value>
            <value>
                <fullName>Sent to patient</fullName>
            </value>
            <value>
                <fullName>Discuss at consultation</fullName>
            </value>
            <value>
                <fullName>Sent to patient (automated)</fullName>
            </value>
            <value>
                <fullName>Auto-send to patient</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Sample_Date__c.field-meta.xml
<CustomField>
    <fullName>Sample_Date__c</fullName>
    <description>Date that the blood sample was analysed</description>
    <inlineHelpText>Date that the blood sample was analysed</inlineHelpText>
    <label>Sample Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Blood_Test__c/fields/Testosterone__c.field-meta.xml
<CustomField>
    <fullName>Testosterone__c</fullName>
    <label>Testosterone</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>The Patient&#39;s Gender - Male/Female. Defaults to Male.</description>
    <inlineHelpText>The Patient&#39;s Gender - Male/Female</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
                <default>true</default>
                <label>Male</label>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Patient_ID__c.field-meta.xml
<CustomField>
    <fullName>Patient_ID__c</fullName>
    <displayFormat>PID-{000000}</displayFormat>
    <label>Patient ID</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/classes/SendDynamicEmail.cls
public class SendDynamicEmail {
    
    @InvocableMethod(label='Send Dynamic Email' description='Send Email with input paramters')
    public static void execute(List<Requests> requestList) {
        if( requestList.size() > 0 ){ 
            String recordId = requestList[0].recId;
            
            Blood_Test__c bTestRec = [Select Id,Name,Results_Status__c  ,Contact__c,Testosterone__c ,Free_Testosterone__c , Sample_Date__c   from Blood_Test__c Where Id =: recordId LIMIT 1];
            Contact patientRec = [SELECT Date_of_Birth__c,LastName,Email,FirstName,Name,Patient_ID__c, Gender__c FROM Contact WHERE Id = :bTestRec.Contact__c LIMIT 1 ];
            
            Id emailtemp = requestList[0].templateId;
            OrgWideEmailAddress orgEmail = [SELECT Id, Address,DisplayName FROM OrgWideEmailAddress WHERE DisplayName = 'bloods@optimale.co.uk'];
            List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();
            String[] toAddresses = new String[] {patientRec.Email};
                
                System.debug('@@@@ '+ patientRec.Email);
            System.debug('@@@@ '+ emailtemp);
            System.debug('@@@@ '+ orgEmail.Address);
            System.debug('@@@@ '+ orgEmail.DisplayName);
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTemplateId(emailtemp);
            mail.setCcAddresses(toAddresses);
            mail.setSaveAsActivity(true);
            mail.setWhatId( bTestRec.Id);
            mail.setTargetObjectId(patientRec.Id);
            mail.setOrgWideEmailAddressId(orgEmail.Id);
            //mail.setReplyTo(orgEmail.Address); 
            //mail.setSenderDisplayName(orgEmail.DisplayName); 
            emailMessages.add(mail);
            Messaging.SendEmailResult[] results = Messaging.sendEmail(emailMessages, false);
        }
    }
    
    public class Requests {
        @InvocableVariable(label='Record Id' description='Record Id' required=true)
        public String recId;
        
        @InvocableVariable(label='Email Temaplate Id' description='Record Id of the Email Temaplate' required=true)
        public String templateId;
    }

}